# Generated by Django 5.2.8 on 2025-11-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_student_enrollment_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='m_ki_c_Admin',
        ),
    ]
