# Generated by Django 5.2.4 on 2026-01-02 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subscribers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserDataAdmin',
            fields=[
                ('userdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='memory.userdata')),
            ],
            bases=('memory.userdata',),
        ),
    ]
