# Generated by Django 5.2.4 on 2026-01-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_userdata_userdataadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDataAdmin',
        ),
    ]
