# Generated by Django 5.2.8 on 2025-11-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Enter a Course Name.', max_length=15, null=True)),
                ('price', models.FloatField(default=0.0, help_text='Choose your course price.')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
