# Generated by Django 5.2.4 on 2025-12-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('content', models.TextField()),
                ('catagory', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
