# Generated by Django 5.2.4 on 2025-12-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apgi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
